name: Madsir Studio
title: Madsir Studio presents ...
markdown: kramdown
permalink: /RemoteAgentGame
permalink: /RemoteAgentGameplay
permalink: /RemoteAgentDemo
url: "https://madsirstudio.com" # the base hostname & protocol for your site

twitter:
  username: madsirstudio
  card: summary

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
