name: Madsir Studio
title: Madsir Studio presents ...
markdown: kramdown
url: "http://madsirstudio.com" # the base hostname & protocol for your site
permalink: /about/
permalink: /RemoteAgentGame/
permalink: /RemoteAgentRadio/
permalink: /secretcodes/
permalink: /Privacy/


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
