name: Madsir Studio
title: Madsir Studio presents ...
markdown: kramdown
permalink: /RemoteAgentGame
url: "https://madsirstudio.com" # the base hostname & protocol for your site


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
