name: Madsir Studio
title: Madsir Studio presents ...
markdown: kramdown
permalink: /RemoteAgentGame
permalink: /RemoteAgentGameplay
permalink: /RemoteAgentDemo
permalink: /chinchillin
permalink: /updates
url: "https://madsirstudio.com" # the base hostname & protocol for your site
theme: jekyll-theme-architect
twitter:
  username: madsirstudio
  card: summary

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
