name: Madsir Studio
title: Madsir Studio presents ...
markdown: kramdown
url: "http://madsirstudio.com" # the base hostname & protocol for your site
permalink: /about/
permalink: /contact/
permalink: /remoteagent/
permalink: /cutscheme2d/
permalink: /privacy/
permalink: /chinchillin
permalink: /utterer
permalink: /spatoots


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
